# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d0a676476a5c6024db77254817177d2dde85c4eb218e06f39828e26ce77144488997ab8e711227c27f0384552eb131ea77cd8ec661045bc39729166731cd5d5

test:
  secret_key_base: 39ca079976e69c1db2bb95bbb3890673fa61407a1ed1a1dab25830c062e0a4af5224a6b1f9409b3c8e09f9c3e61a9bf6634743c976e5c55a0f9b71132096b644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id:  'AKIAJ55FNIO3JKNVSFOQ'
  # シークレットキー
  aws_secret_access_key: 'vtWfPZQ8r8i/KmILlSwceZCb3P9KZWai8uhunOM/'
  # Tokyo
  region:  'ap-northeast-1'